### ISSUE TITLE
Performing physical delete

### ISSUE THREAD

**Issue by jadsonbr** [jeanphix/sqla-paranoid#2]
Using the library how to do physical delete ?

@jeanphix

**Comment by jeanphix** [comment]
Think we could add a boolean argument here https://github.com/jeanphix/sqla-paranoid/blob/dev/paranoid/models.py#L83 to bypass the soft delete.

You need it ?

**Comment by jadsonbr** [comment]
Yes, I need it.
I use softdelete more in some cases in specific I have the need to make the physical delete.
I would be very grateful to have this functionality.

**Comment by jeanphix** [comment]
Ok, will add it very soon.

**Comment by jadsonbr** [comment]
Already have some news?

@jeanphix

**Comment by jeanphix** [comment]
https://github.com/jeanphix/sqla-paranoid/commit/fc41210d3ec9563b27b13bda9a258d2dcc7ecc5f#diff-6e942efa311df55ff40f792862a4275bR144

Sorry, a bit late... Released on pypi.

**Comment by jadsonbr** [comment]
@jeanphix 
Thank you
